name: athlorygymapp2
description: "A Flutter project with localization, theming, and state management support."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # Lokalisierungspaket
    sdk: flutter
  provider: ^6.1.2  # Kompatible Version für State Management
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Kompatible Version für Linter

flutter:
  uses-material-design: true